### ISSUE TITLE
Client retains ownership of objects when in dungeons

### ISSUE THREAD

**Issue by Lughbaloo** [JereKuusela/valheim-dungeon_splitter#1]
Hello,

I have Dungeon splitter version 1.1.0 installed on both Client and Server. When players enter a dungeon, if they are the owner of the zone, all nearby enemies freeze in place for other players. I've double-checked that the mod is indeed loaded on server boot and loaded on client boot.

I saw this blurb on the README for if the mod is only installed on clients.
-Client may retain ownership of unloaded objects which can make them appear frozen for other players.

**Comment by JereKuusela** [comment]
This might be now fixed, the mod is bit difficult to test.
